### ISSUE TITLE
Error Message When Trying to Download Roblox Through BloxMgr

### ISSUE THREAD

**Issue by allFictionAS** [sdhEmily/RobloxPatcher#2]
Mac Details: MacOS Sonoma (1 update behind), M1 MacBook Air 2020 8GB

Happens whenever trying to download roblox from the terminal

Error log:

```
ℹ️  Downloading ROBLOX...
ℹ️  Extracting...
ℹ️  Applying Mods...
ℹ️  Applying FFlags...
Traceback (most recent call last):
  File "/tmp/BloxMgr.py", line 318, in <module>
    mainmenu()
  File "/tmp/BloxMgr.py", line 67, in mainmenu
    elif '3' in answer: update()
                        ^^^^^^^^
  File "/tmp/BloxMgr.py", line 263, in update
    file_content = json.load(infile)
                   ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sdhEmily** [comment]
your flag list contains invalid json somewhere
i'm planning to add a handler for that soon but i don't have access to my mac atm

**Comment by allFictionAS** [comment]
lol made the rookie mistake of not saving the .json on VSC
